### ISSUE TITLE
write unix /var/run/docker.sock->@: write: broken pipe

### ISSUE THREAD

**Issue by drsect0r** [docker-php/docker-php#195] opened 2016-04-21 08:20 UTC
I'm sending commands to different containers; this was working correctly until a few days ago. Since then, the only thing that changed is; a new Docker version was released and I switched from a TCP connection to a socket connection. Rest of the commands execute fine. 

Information: 

``` shell
$ php -v
PHP 7.0.5-1~dotdeb+8.1 (cli) ( NTS )

$ docker -v 
Docker version 1.11.0, build 4dc5990

$ uname -a
Linux docker-host 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux

$ cat /etc/issue
Debian GNU/Linux 8 \n \l
```

```
Apr 21 07:35:46 docker-host docker[11709]: time="2016-04-21T07:35:46.790486036Z" level=error msg="attach: stdout: write unix /var/run/docker.sock->@: write: broken pipe"
Apr 21 07:35:46 docker-host docker[11709]: time="2016-04-21T07:35:46.931491694Z" level=error msg="Error running exec in container: attach failed with error: write unix /var/run/docker.sock->@: write: broken pipe\n"
Apr 21 07:35:46 docker-host docker[11709]: time="2016-04-21T07:35:46.931563085Z" level=error msg="Handler for POST /exec/fc6c278bc319d31ae125e6bfe62aab3bed6ae54d64223597e2c7a367fd540153/start returned error: attach failed with error: write unix /var/run/docker.sock->@: write: broken pipe"
Apr 21 07:35:46 docker-host docker[11709]: 2016/04/21 07:35:46 http: response.WriteHeader on hijacked connection
Apr 21 07:35:46 docker-host docker[11709]: 2016/04/21 07:35:46 http: response.Write on hijacked connection
```

**Update**: The problem occurs also when using a TCP connection:
**Update**: When using a TCP connection there are less of these errors then when using a socket connection. 

```
Apr 21 08:33:24 docker-host docker[25468]: time="2016-04-21T08:33:24.772961231Z" level=error msg="attach: stderr: write tcp 10.99.0.99:2375->172.17.0.2:40968: write: broken pipe"
Apr 21 08:33:25 docker-host docker[25468]: time="2016-04-21T08:33:25.890528192Z" level=error msg="Error running exec in container: attach failed with error: write tcp 10.99.0.99:2375->172.17.0.2:40968: write: broken pipe\n"
Apr 21 08:33:25 docker-host docker[25468]: time="2016-04-21T08:33:25.890563806Z" level=error msg="Handler for POST /exec/aca8b3206f70586afa35766edf858827b57dd1e7a5643878df1996c8c818f061/start returned error: attach failed with error: write tcp 10.99.0.99:2375->172.17.0.2:40968: write: broken pipe"
Apr 21 08:33:25 docker-host docker[25468]: 2016/04/21 08:33:25 http: response.WriteHeader on hijacked connection
Apr 21 08:33:25 docker-host docker[25468]: 2016/04/21 08:33:25 http: response.Write on hijacked connection
```

Docker issue: https://github.com/docker/docker/issues/22221

**Comment by drsect0r** [comment] 2016-04-22 12:15
I did a downgrade to Docker version 1.10.2. This version is working for me. I do still get partial error messages. The command did executed correctly.
```
Apr 22 12:11:19 docker-host docker[11787]: time="2016-04-22T12:11:19.080010253Z" level=error msg="attach: stdout: write unix /var/run/docker.sock->@: write: broken pipe"
Apr 22 12:11:19 docker-host docker[11787]: time="2016-04-22T12:11:19.109409630Z" level=error msg="Error running exec in container: attach failed with error: write unix /var/run/docker.sock->@: write: broken pipe\n"
```

**Comment by sroze** [comment] 2016-06-06 14:15
I'm experiencing the same issue with Docker 1.9.1.

**Comment by sroze** [comment] 2016-06-07 12:34
FYI, I upgraded and the problem is solved. Behind, it was an 400 response from the Docker daemon.

**Comment by joelwurtz** [comment] 2018-03-01 15:30
Networks errors, are mainly due to the socket lib used, however there is so many reasons when this can happens, i don't think there is a good way to fix that.

One of the possibility, if you have bad network, would be to add the RetryPlugin of php-http.

Closing this, dont hesite to reopen it, if you can produce a reproducible use case.

**Closed by joelwurtz** 2018-03-01 15:30 UTC
