### ISSUE TITLE
Duplicate build context/process from docker cli to be more compatible

### ISSUE THREAD

**Issue by hacfi** [docker-php/docker-php#92] opened 2015-02-01 05:06 UTC
Playing around with `Docker::build` I noticed that the cache checksums displayed during the build process aren’t the same as the ones from docker cli. Looks like the build context isn’t created the same way. Ideally we find out why and adapt `Docker\Context`.

**Comment by hacfi** [comment] 2015-02-05 14:28
The issue is very difficult to debug due to Docker receiving, extracting and processing the build context on the fly. I’ll still try to find out why this is happening.

**Comment by joelwurtz** [comment] 2018-01-06 14:57
Will close this as i was unable to reproduce this issue

**Closed by joelwurtz** 2018-01-06 14:57 UTC
Labels: enhancement
