### ISSUE TITLE
How to setup volumes?

### ISSUE THREAD

**Issue by ebuildy** [docker-php/docker-php#115] opened 2015-04-28 07:01 UTC
I am sorry to post this as an issue but I didn't find anything about it in documentation and former issues.

In Container class I can see we can easily manage ports, but what about volumes?

Thanks,

Thomas Decaux

**Comment by hacfi** [comment] 2015-04-28 09:58
@ebuildy What do you want to do exactly? Map a volume from another container or the host?

**Comment by ebuildy** [comment] 2015-04-28 10:00
Yes, I want run a container with a volume attached.

**Comment by hacfi** [comment] 2015-04-28 10:10
@ebuildy I don’t have time to try this out right now but you can try if something like the following works:

``` php
$container = new \Docker\Container([
    'Image' => 'ubuntu:trusty',
    'Volumes' => [
        '/tmp' => []
    ]
    'HostConfig' => [
      'Binds': ['/tmp:/tmp'],
      'VolumesFrom': ['other_container', 'containerX:ro'],
    ]
]);
$docker->getContainerManager()->run($container);
```

**Comment by ubermuda** [comment] 2015-04-28 13:16
I can confirm the `Binds` part because I use it personally. `VolumesFrom` should work just as well. 

Volumes are an area that obviously needs a bit more abstraction :)

**Comment by aarobc** [comment] 2016-03-14 16:55
@hacfi I tried your example, but that outputs the error: `Class 'Docker\Docker\Container' not found`. 
Assuming you just got the path off, I revised the namespace used to `$container = new \Docker\API\Model\Container([` but then it didn't like the colon. changing that to `=>` then gives an error:
`Docker\Manager\ContainerManager::run()` so I'm probably pursing the wrong path. 

could you elaborate on your solution?

**Comment by ebuildy** [comment] 2016-05-11 10:41
ContainerManager method run seems not existing?

And Swagger container model has no ``Volumes`` field .....

**Comment by joelwurtz** [comment] 2016-05-11 12:50
The example above is from an old version of docker-php so it's no longer working, and yes i just see i don't no take into account the `Volumes` property for a container.

There is actually a big mix up in the model for container for listing / creation i will refactor this part as it's a complete mess.

The run method does not exist as it's not part of the API (in fact when you do a run with the docker client it's doing multiple calls to the API : create -> attach -> start -> wait)

**Comment by dontub** [comment] 2016-06-17 12:06
As far as I understand the API there should be `Volumes` in `ContainerConfig` instead of `Mounts`.

**Comment by joelwurtz** [comment] 2018-03-01 15:18
There is no documentation about it, but proprety volumes is definitely present in docker 2.0, will close this, if somebody wants to write a cookbook about it i would gladly merge this into the documentation.

**Closed by joelwurtz** 2018-03-01 15:18 UTC
Labels: documentation
